logging:
  config: classpath:config/logback-dev.xml
server:
  port: 8080

spring:
  datasource:
    username: array
    password: array@hdu
    url: jdbc:mysql://10.1.21.152:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver
  web:
    loginurl: http://localhost:${server.port}/swagger-ui.html
    isopenurl: true
    googleexcute: explorer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hdu.blog.entity

